FROM ubuntu:latest

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    git \
    curl \
    unzip \
    xvfb \
    firefox \
    && apt-get clean

RUN pip3 install --upgrade pip \
    && pip3 install \
    robotframework \
    robotframework-faker \
    Faker \
    robotframework-requests \
    robotframework-jsonlibrary

RUN mkdir -p /opt/robotframework/tests /opt/robotframework/results
VOLUME /opt/robotframework/results
VOLUME /opt/robotframework/tests

WORKDIR /opt/robotframework

CMD robot --outputdir /opt/robotframework/results /opt/robotframework/tests